
set(ENABLED_GEMS
    PotatoInSpace
    Atom
    AudioSystem
    AWSCore
    CameraFramework
    DebugDraw
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    Multiplayer
    PhysX
    PrimitiveAssets
    PrefabBuilder
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    WhiteBox
    Achievements
    AssetValidation
    AtomContent
    DccScriptingInterface
    AtomLyIntegration
    AtomTressFX
    AutomatedTesting
    BarrierInput
    Camera
    CrashReporting
    CustomAssetExample
    DevTextures
    FastNoise
    GameStateSamples
    Gestures
    HttpRequestor
    InAppPurchases
    Maestro
    Metastream
    Microphone
    MotionMatching
    MultiplayerCompression
    Blast
    NvCloth
    PhysXDebug
    Presence
    Profiler
    PythonCoverage
    QtForPython
    SceneLoggingExample
    SceneProcessing
    ScriptCanvasDeveloper
    ScriptCanvasTesting
    ScriptedEntityTweener
    SliceFavorites
    StartingPointCamera
    StartingPointMovement
    Terrain
    TestAssetBuilder
    TickBusOrderViewer
    Twitch
    VideoPlaybackFramework
    VirtualGamepad
    AudioEngineWwise
)
